name: cover_ops
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  args: '^2.4.2'
  dcli: any

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
