name: cover_ops
description: A sample command-line application.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.5.3

dependencies:
  args: "^2.4.2"
  dcli: any
  process:
    git:
      url: https://github.com/kannel-outis/process.git

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

sub_modules:
  - path: ./packages/git_parser_cli
  - path: ./packages/lcov_cli
  - path: ./packages/html_gen
