name: lcov_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  args: '^2.4.2'
  dcli: ^7.0.2
  file: ^7.0.0
  html_gen:
    path: ../html_gen
  cli_table: ^1.0.2

dev_dependencies:
  lints: ^4.0.0
  coverage: ^1.7.2
  test: ^1.24.0
