name: html_gen
description: HTML Gen is a Dart package that provides an object-oriented approach to generating HTML markup.
version: 1.0.0
repository: https://github.com/kannel-outis/CoverOps/tree/main/packages/html_gen

environment:
  sdk: ^3.5.3


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0


topics: 
  - html
  - generator

