name: html_gen
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/kannel-outis/CoverOps.git

environment:
  sdk: ^3.5.3


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
