name: PR Code coverage Report

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
    paths:
      - "**.dart"

jobs:
  analyze_code:
    name: Analyze code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup & install Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: |
          cd .github
          make all

      - name: Run Tests
        run: |
          cd .github
          make test

      - name: Run CoverOps
        run: |
          cd .github
          make report
